### ISSUE TITLE
reactatouille "project name" command fails on Windows

### ISSUE THREAD

**Issue by rjabreu** [heldrida/reactatouille-boilerplate#1]
OS: Windows 10 - build 14393

Running the command: `reactatouille <project name>` throws error on windows.

 The output is:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn clear ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by heldrida** [comment]
Fix path issue on windows, please do:
`
npm install -g reactatouille@latest`

**Comment by rjabreu** [comment]
@heldrida  can confirm its working now. thanks!
